### ISSUE TITLE
Getting 502 Bad Gateway when running container with Evergreen 3.11.7

### ISSUE THREAD

**Issue by IanSkelskey** [mcoia/eg-docker#27]
502 Bad Gateway
nginx/1.18.0 (Ubuntu)

**Comment by bmagic007** [comment]
IanSkelskey - are you referring to the DEV container build?

**Comment by IanSkelskey** [comment]
> IanSkelskey - are you referring to the DEV container build?

Yessir

**Comment by bmagic007** [comment]
OK, that makes sense. The DEV container is meant to hack on Evergreen main branch. The container is built on Evergreen code closer to main. It's likely not* going to work when trying to launch it with older code. It's not supposed to.

So, if you need to hack on older Evergreen code, maybe you could make use of the pre-built containers for the version? It's not going to work with your local Evergreen folder (like the DEV container does), so, you'll have to a bit of finessing to edit the internal-code in the container.

For example:

docker run -it -p 80:80 -p 443:443 -p 210:210 -p 6001:6001 -p 32:22 -p 5433:5432 -h app.evergreen.com mobiusoffice/evergreen-ils:3.11.4

will download and boot a self-contained Evergreen server running 3.11.4. If you want to share some folders, you can throw in some mounts, and work out some custom way of getting your changes into the running-config.

Sorry! Hacking older versions of Evergreen was something that came to mind when I designed the DEV container, and decided that we wouldn't support it. We should probably update the README to make that clear about the DEV container.

**Comment by bmagic007** [comment]
Ian,

That said, you could build your own DEV container built from 3.11.7. Before building, make sure you edit vars.yml to indicate the version of Evergreen. And this line:

evergreen_git_branch: main

needs to be switched to

evergreen_git_branch: tags/rel_3_11_7

Alternatively, you could change the line to correspond to your previous evergreen_version| variable:

evergreen_git_branch: "{{ 'tags/rel_' + (evergreen_version|regex_replace('\\.', '_')) }}"

The other consideration is the version of Postgres. I happen to know that Evergreen 3.11 works on PG15, but if you're wanting to mirror your production environment, then you might want to that to be PG10. That variable is:

postgres_version

You could manually set that to "10" or whatever number you like. Mileage may vary.

-Blake-

**Comment by IanSkelskey** [comment]
Thanks for getting back to me on this. I had some trouble building the container from my local changes last time and it wasn't super important in the moment so I dropped it temporarily. Now, I think I'll give it another go. Bibliomation stays behind the community by a version or two deliberately so I will always have a need to build older versions of Evergreen on the fly.
