### ISSUE TITLE
It would be nice if ansible tasks had unique names

### ISSUE THREAD

**Issue by sandbergja** [mcoia/eg-docker#5]
This is just a convenience factor if you want to use `--start-at-task`.  For example, evergreen_restart_services.yml has three different tasks named "Kill ejabberd", so `--start-at-task="Kill ejabberd"` may or may not start running the playbook at the intended task.

**Comment by bmagic007** [comment]
Resolved with commit 36873fe6f69d39890475e7dd96e85251aa2683b8
